"""empty message

Revision ID: ba5487b708f4
Revises: a9c784ca915c
Create Date: 2022-10-21 23:51:01.855495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba5487b708f4'
down_revision = 'a9c784ca915c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite')
    op.drop_index('name', table_name='people')
    op.drop_index('name_2', table_name='people')
    op.drop_table('people')
    op.drop_index('name', table_name='planet')
    op.drop_index('name_2', table_name='planet')
    op.drop_table('planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('climate', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('population', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('orbital_period', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('rotation_period', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('diameter', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'planet', ['name'], unique=False)
    op.create_index('name', 'planet', ['name'], unique=False)
    op.create_table('people',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mass', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skin_color', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('birth_year', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('eye_color', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'people', ['name'], unique=False)
    op.create_index('name', 'people', ['name'], unique=False)
    op.create_table('favourite',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='favourite_ibfk_1'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favourite_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favourite_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
